artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL : https://github.com/MoraisMNS/billsumdataset/raw/refs/heads/main/billsum_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_COLUMNS: ["text", "summary", "title"]  # adapt as needed


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/billsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/billsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/billsum_dataset
  model_path: artifacts/model_trainer/pegasus-billsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv
